Daily Challenge

In [9]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/W2/D3/datascience_salaries.csv")
data.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000

In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

# Création du DataFrame
df = pd.DataFrame(data)

# 1. Normalisation Min-Max de la colonne 'salary'
scaler = MinMaxScaler()
df['salary_normalized'] = scaler.fit_transform(df[['salary']])

# 2. Supposons qu'il y ait d'autres features numériques pour PCA
# Pour l'exemple, créons des features artificielles
np.random.seed(0)
df['feature1'] = np.random.rand(len(df))
df['feature2'] = np.random.rand(len(df))
features = ['salary_normalized', 'feature1', 'feature2']

# 3. Application de PCA pour réduire à 2 composants
pca = PCA(n_components=2)
principal_components = pca.fit_transform(df[features])
df_pca = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])

# Ajout des composants PCA au DataFrame original (optionnel)
df = pd.concat([df, df_pca], axis=1)

# 4. Groupement par 'experience_level' et calcul de la moyenne et médiane du salaire
grouped_stats = df.groupby('experience_level')['salary'].agg(['mean', 'median']).reset_index()

# Affichage des résultats
print("DataFrame avec salaires normalisés et PCA :")
print(df[['salary', 'salary_normalized', 'PC1', 'PC2']])
print("\nMoyenne et médiane des salaires par niveau d'expérience :")
print(grouped_stats)

DataFrame avec salaires normalisés et PCA :
      salary  salary_normalized       PC1       PC2
0     149000           0.601010 -0.121370 -0.052527
1     120000           0.454545 -0.171335  0.135183
2      68000           0.191919 -0.023759  0.128455
3     120000           0.454545  0.301690  0.364973
4     149000           0.601010  0.185994  0.076359
...      ...                ...       ...       ...
1166  228000           1.000000 -0.350716 -0.229249
1167  115000           0.429293 -0.059932 -0.147790
1168   76000           0.232323  0.054842  0.481838
1169   68000           0.191919 -0.607088  0.001046
1170  135000           0.530303 -0.104692 -0.386414

[1171 rows x 4 columns]

Moyenne et médiane des salaires par niveau d'expérience :
  experience_level          mean   median
0            Entry  36111.111111  30000.0
1        Executive  76076.923077  46000.0
2              Mid  51786.885246  51000.0
3           Senior  75088.033012  68000.0